/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{													//Pg 65, 265, 287, 288
	uint32_t *pClkCtrlReg =   (uint32_t*)0x40023830;//0x40023800 [BASE] + 0x30 [OFFSET]
	uint32_t *pPortDModeReg = (uint32_t*)0x40020C00;//0x40020C00 [BASE] + 0x00 [OFFSET]
	uint32_t *pPortDOutReg =  (uint32_t*)0x40020C14;//0x40020C14 [BASE] + 0x14 [OFFSET]

	//1. enable the clock for GPOID peripheral in the RCC_AHB1ENR (SET the 3rd bit position)
	*pClkCtrlReg |= ( 1 << 3);

	//2. configure the mode of the IO pin 12 as output
	//a. set the 24th and clear 25th bit positions
	*pPortDModeReg &= ~( 1 << 25);
	//b. make 24th bit position as 1 (SET)
	*pPortDModeReg |= ( 1 << 24);

	//3.SET 8th bit of the output data register to make I/O pin-8 as HIGH
	*pPortDOutReg |= ( 1 << 12);

    while(1);
}
